name: Hello

on: [push]

jobs:
  greet:

    runs-on: ubuntu-latest
    
    steps:
      - id: hello_world
        name: Hello World
        uses: jackducham/mm26-design/.github/actions@master
        with:
          who-to-greet: 'jack'
