name: Set Tags

on:
  issues:
    types: [opened, reopened]

jobs:
  label:

    runs-on: ubuntu-latest
    
    steps:
      - id: label
        name: Add Label
        uses: jackducham/mm26-design/.github/actions@master
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          label: 'Team: Design'
